#[derive(Debug, Clone)]
pub struct SourceDef {
    pub name: &'static str,
    pub url: &'static str,
    pub feed_url: Option<&'static str>,
    pub tier: i32,
    pub scrape_method: &'static str,
    pub is_paywalled: bool,
    pub enabled: bool,
}

pub fn all_sources() -> Vec<SourceDef> {
    vec![
        // ── Tier 1 (Core) ──
        SourceDef {
            name: "Spike Art Magazine",
            url: "https://www.spikeartmagazine.com",
            feed_url: Some("https://www.spikeartmagazine.com/?format=rss"),
            tier: 1,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: true,
        },
        SourceDef {
            name: "The New Yorker",
            url: "https://www.newyorker.com",
            feed_url: Some("https://www.newyorker.com/feed/culture"),
            tier: 1,
            scrape_method: "rss",
            is_paywalled: true,
            enabled: true,
        },
        SourceDef {
            name: "NYT Arts",
            url: "https://www.nytimes.com/section/arts/design",
            feed_url: Some("https://rss.nytimes.com/services/xml/rss/nyt/ArtandDesign.xml"),
            tier: 1,
            scrape_method: "rss",
            is_paywalled: true,
            enabled: true,
        },
        SourceDef {
            name: "NYT T Magazine",
            url: "https://www.nytimes.com/section/t-magazine",
            feed_url: Some("https://rss.nytimes.com/services/xml/rss/nyt/tmagazine.xml"),
            tier: 1,
            scrape_method: "rss",
            is_paywalled: true,
            enabled: true,
        },
        SourceDef {
            name: "Cultured Magazine",
            url: "https://www.culturedmag.com",
            feed_url: Some("https://www.culturedmag.com/feed/"),
            tier: 1,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: true,
        },
        SourceDef {
            name: "Dazed",
            url: "https://www.dazeddigital.com",
            feed_url: Some("https://www.dazeddigital.com/rss"),
            tier: 1,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: true,
        },
        SourceDef {
            name: "Hacker News",
            url: "https://news.ycombinator.com",
            feed_url: Some("https://hnrss.org/newest?q=art+design+creative"),
            tier: 1,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: true, // intermittent 502s, keep enabled
        },
        SourceDef {
            name: "Harper's Magazine",
            url: "https://harpers.org",
            feed_url: Some("https://harpers.org/feed/"),
            tier: 1,
            scrape_method: "rss",
            is_paywalled: true,
            enabled: true,
        },
        SourceDef {
            name: "The Creative Independent",
            url: "https://thecreativeindependent.com",
            feed_url: Some("https://thecreativeindependent.com/feed/"),
            tier: 1,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: false, // 403 persists
        },
        SourceDef {
            name: "n+1",
            url: "https://www.nplusonemag.com",
            feed_url: Some("https://www.nplusonemag.com/feed/"),
            tier: 1,
            scrape_method: "rss",
            is_paywalled: true,
            enabled: false, // 403 persists
        },
        SourceDef {
            name: "Brooklyn Rail",
            url: "https://brooklynrail.org",
            feed_url: Some("https://brooklynrail.org/rss.xml"),
            tier: 1,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: false, // 404 on all known feed URLs
        },
        SourceDef {
            name: "Gagosian Quarterly",
            url: "https://gagosian.com/quarterly/",
            feed_url: Some("https://gagosian.com/quarterly/feed/"),
            tier: 1,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: false, // 404 persists
        },
        SourceDef {
            name: "Asterisk",
            url: "https://asteriskmag.com",
            feed_url: Some("https://asteriskmag.com/feed"),
            tier: 1,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: true,
        },
        SourceDef {
            name: "Hyperallergic",
            url: "https://hyperallergic.com",
            feed_url: Some("https://hyperallergic.com/feed/"),
            tier: 1,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: true,
        },
        SourceDef {
            name: "Artforum",
            url: "https://www.artforum.com",
            feed_url: Some("https://www.artforum.com/feed/"),
            tier: 1,
            scrape_method: "rss",
            is_paywalled: true,
            enabled: true,
        },
        SourceDef {
            name: "Art in America",
            url: "https://www.artnews.com/c/art-in-america/",
            feed_url: Some("https://www.artnews.com/c/art-in-america/feed/"),
            tier: 1,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: true,
        },
        SourceDef {
            name: "ARTnews",
            url: "https://www.artnews.com",
            feed_url: Some("https://www.artnews.com/feed/"),
            tier: 1,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: true,
        },
        SourceDef {
            name: "Artsy Editorial",
            url: "https://www.artsy.net",
            feed_url: Some("https://www.artsy.net/rss/news"),
            tier: 1,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: true,
        },
        SourceDef {
            name: "Bomb Magazine",
            url: "https://bombmagazine.org",
            feed_url: Some("https://bombmagazine.org/rss"),
            tier: 1,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: false, // 404 on all known feed URLs
        },
        SourceDef {
            name: "The Art Newspaper",
            url: "https://www.theartnewspaper.com",
            feed_url: Some("https://www.theartnewspaper.com/rss"),
            tier: 1,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: false, // 404 on /rss and /feed
        },
        SourceDef {
            name: "Contemporary Art Daily",
            url: "https://contemporaryartdaily.com",
            feed_url: Some("https://contemporaryartdaily.com/feed/"),
            tier: 1,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: true,
        },
        SourceDef {
            name: "Mousse Magazine",
            url: "https://www.moussemagazine.it",
            feed_url: Some("https://www.moussemagazine.it/feed/"),
            tier: 1,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: true,
        },
        // ── Tier 2 (Discovery) ──
        SourceDef {
            name: "Fakewhale",
            url: "https://fakewhale.art",
            feed_url: Some("https://fakewhale.art/feed/"),
            tier: 2,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: false, // consistently fails
        },
        SourceDef {
            name: "Public Domain Review",
            url: "https://publicdomainreview.org",
            feed_url: Some("https://publicdomainreview.org/rss.xml"),
            tier: 2,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: true,
        },
        SourceDef {
            name: "Flash Art",
            url: "https://flash---art.com",
            feed_url: Some("https://flash---art.com/feed/"),
            tier: 2,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: true,
        },
        SourceDef {
            name: "Kunstkritikk",
            url: "https://kunstkritikk.com",
            feed_url: Some("https://kunstkritikk.com/feed/"),
            tier: 2,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: true,
        },
        SourceDef {
            name: "Pioneer Works",
            url: "https://pioneerworks.org",
            feed_url: Some("https://pioneerworks.org/broadcast/feed/"),
            tier: 2,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: false, // 500 persists
        },
        SourceDef {
            name: "The Drift",
            url: "https://www.thedriftmag.com",
            feed_url: Some("https://www.thedriftmag.com/feed/"),
            tier: 2,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: false, // 403 persists
        },
        SourceDef {
            name: "Rhizome",
            url: "https://rhizome.org",
            feed_url: Some("https://rhizome.org/editorial/feed/"),
            tier: 2,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: false, // 403 persists
        },
        SourceDef {
            name: "Momus",
            url: "https://momus.ca",
            feed_url: Some("https://momus.ca/feed/"),
            tier: 2,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: false, // connection fails
        },
        SourceDef {
            name: "Elephant Magazine",
            url: "https://elephant.art",
            feed_url: Some("https://elephant.art/feed/"),
            tier: 2,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: true,
        },
        SourceDef {
            name: "e-flux Journal",
            url: "https://www.e-flux.com/journal/",
            feed_url: Some("https://www.e-flux.com/journal/rss/"),
            tier: 2,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: false, // 404 on all known feed URLs
        },
        SourceDef {
            name: "e-flux Announcements",
            url: "https://www.e-flux.com",
            feed_url: Some("https://e-flux.com/rss/"),
            tier: 2,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: false, // 404 on all known feed URLs
        },
        SourceDef {
            name: "Frieze",
            url: "https://www.frieze.com",
            feed_url: Some("https://frieze.com/feed"),
            tier: 2,
            scrape_method: "rss",
            is_paywalled: true,
            enabled: false, // 403 persists, heavy paywall
        },
        SourceDef {
            name: "Ocula",
            url: "https://ocula.com",
            feed_url: Some("https://ocula.com/magazine/rss/"),
            tier: 2,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: false, // 403 persists
        },
        SourceDef {
            name: "Aperture",
            url: "https://aperture.org",
            feed_url: Some("https://aperture.org/feed/"),
            tier: 2,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: false, // 403 persists
        },
        SourceDef {
            name: "Art Agenda",
            url: "https://www.art-agenda.com",
            feed_url: Some("https://www.art-agenda.com/rss/"),
            tier: 2,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: false, // 404
        },
        SourceDef {
            name: "Artnet News",
            url: "https://news.artnet.com",
            feed_url: Some("https://news.artnet.com/feed/"),
            tier: 2,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: true,
        },
        SourceDef {
            name: "The White Pube",
            url: "https://www.thewhitepube.co.uk",
            feed_url: Some("https://www.thewhitepube.co.uk/feed"),
            tier: 2,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: false, // feed parse error
        },
        // ── Tier 3 (Indie) ──
        SourceDef {
            name: "Piper Haywood",
            url: "https://piperhaywood.com",
            feed_url: Some("https://piperhaywood.com/feed/"),
            tier: 3,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: true,
        },
        SourceDef {
            name: "Tom Critchlow",
            url: "https://tomcritchlow.com",
            feed_url: Some("https://tomcritchlow.com/feed.xml"),
            tier: 3,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: true,
        },
        SourceDef {
            name: "Laurel Schwulst",
            url: "https://laurelschwulst.com",
            feed_url: Some("https://laurelschwulst.com/feed/"),
            tier: 3,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: false, // 404
        },
        SourceDef {
            name: "Arachne",
            url: "https://arachne.substack.com",
            feed_url: Some("https://arachne.substack.com/feed"),
            tier: 3,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: true,
        },
        SourceDef {
            name: "The Intrinsic Perspective",
            url: "https://www.theintrinsicperspective.com",
            feed_url: Some("https://www.theintrinsicperspective.com/feed"),
            tier: 3,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: true,
        },
        SourceDef {
            name: "Henrik Karlsson",
            url: "https://www.henrikkarlsson.xyz",
            feed_url: Some("https://www.henrikkarlsson.xyz/feed"),
            tier: 3,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: true,
        },
        SourceDef {
            name: "Personal Canon",
            url: "https://personalcanon.com",
            feed_url: Some("https://personalcanon.com/feed"),
            tier: 3,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: true,
        },
        SourceDef {
            name: "Noahpinion",
            url: "https://noahpinion.substack.com",
            feed_url: Some("https://noahpinion.substack.com/feed"),
            tier: 3,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: false, // economics/politics, not art
        },
        SourceDef {
            name: "CARLA",
            url: "https://contemporaryartreview.la",
            feed_url: Some("https://contemporaryartreview.la/feed/"),
            tier: 3,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: true,
        },
        // ── Tier 4 (Supplemental) ──
        SourceDef {
            name: "Yale Review",
            url: "https://yalereview.org",
            feed_url: Some("https://yalereview.org/feed"),
            tier: 4,
            scrape_method: "rss",
            is_paywalled: false,
            enabled: false, // 404 persists
        },
        SourceDef {
            name: "New Models",
            url: "https://www.newmodels.io",
            feed_url: None,
            tier: 4,
            scrape_method: "browser",
            is_paywalled: false,
            enabled: false,
        },
        SourceDef {
            name: "Sternberg Press",
            url: "https://www.sternberg-press.com",
            feed_url: None,
            tier: 4,
            scrape_method: "browser",
            is_paywalled: false,
            enabled: false,
        },
        SourceDef {
            name: "Right Click Save",
            url: "https://www.rightclicksave.com",
            feed_url: None,
            tier: 4,
            scrape_method: "browser",
            is_paywalled: false,
            enabled: false,
        },
        SourceDef {
            name: "AtRisk Magazine",
            url: "https://www.atriskmagazine.com",
            feed_url: None,
            tier: 4,
            scrape_method: "browser",
            is_paywalled: false,
            enabled: false,
        },
    ]
}
